### ISSUE TITLE
关于If-None-Match字段的值

### ISSUE THREAD

**Issue by nikoohp** [Joe19970619/Learning-materials#1]
![image](https://user-images.githubusercontent.com/4496368/37750090-145d4476-2dc6-11e8-8ff9-197b76213338.png)

这里说的是为GMT格式的时间字符串，这是不对的吧？
`If-None-Match`的值不应该是上一次返回的`ETag`的值吗？

**Comment by Joe19970619** [comment]
确实，这里写错了，已修改，非常感谢指出问题哈~~~
